In [68]:
# Python code for deterministic inventory by dynamic programming, with numpy

import numpy

hugeNumber = float("inf")

stages             = 4
startInventory     = 0
inventoryCapacity  = 4
productionCapacity = 5

setupCost    = 3.0
variableCost = 1.0
holdingRate  = 0.5
shortageRate = 2.1

# wtf is going on h
demand = numpy.array([-1000,2,2,2,2])    # The zero-th entry is unused here

f = numpy.zeros([stages + 2, inventoryCapacity + 1])
x = numpy.zeros([stages + 1, inventoryCapacity + 1], dtype=int)

for t in range(stages,0,-1) :

    for i in range(inventoryCapacity + 1) :
  
        # minProduction = max(0, demand[t] - i)
        minProduction = 0
        maxProduction = min(productionCapacity, inventoryCapacity - i + demand[t])
    
        value = hugeNumber


        for p in range(minProduction, maxProduction+1):
            productionCost = holdingCost = shortageCost = 0    
            
            j = i + p - demand[t]

            # if there's a shortage, it means we carry forward 0 units.
            if j < 0 :
                j = 0

            if p < demand[t] - i:
                # incur shortage cost
                shortageCost += shortageRate*(demand[t] - i - p)
                holdingCost = 0
                
            elif p > demand[t] - i:
                # j is the amount left over
                holdingCost += holdingRate*(i + p - demand[t])
                shortageCost = 0
                
            
            productionCost = variableCost*p
            if p > 0:
                productionCost += setupCost
            moveValue = holdingCost + shortageCost + productionCost + f[t+1,j]


            if moveValue < value :
                value = moveValue
                bestMove = p
      
        # End of p loop
        f[t,i] = value
        x[t,i] = bestMove
        #print(f)
        # print(x)
    
    # End of i loop
    print(f"value: {value}")
    print(f"bestMove {bestMove}\n\n")    
# End of t loop

print("Optimal cost is " + str(f[1,startInventory]))

solutionString = "Production amounts:"
i = startInventory
for t in range(1,stages+1) :
    if i < 0:
        i = 0
    #print(t)
    solutionString += " " + str(x[t,i])
    #print(solutionString)
    i = i + x[t,i] - demand[t]

print(solutionString)

value: 1.0
bestMove 0


value: 1.0
bestMove 0


value: 5.2
bestMove 0


value: 9.0
bestMove 0


Optimal cost is 16.0
Production amounts: 4 0 4 0
[[ 0.   0.   0.   0.   0. ]
 [16.  14.2 12.1 10.6  9. ]
 [12.1 10.1  8.   6.8  5.2]
 [ 8.   6.3  4.2  2.6  1. ]
 [ 4.2  2.1  0.   0.5  1. ]
 [ 0.   0.   0.   0.   0. ]]
[[0 0 0 0 0]
 [4 0 0 0 0]
 [5 0 0 0 0]
 [4 0 0 0 0]
 [0 0 0 0 0]]
