In [2]:
# Python code for deterministic inventory by dynamic programming, with numpy

import numpy

hugeNumber = float("inf")

stages             = 4
startInventory     = 0
inventoryCapacity  = 4
productionCapacity = 5

setupCost    = 3.0
variableCost = 1.0
holdingCost  = 0.5

demand = numpy.array([-1000,1,3,2,4])    # The zero-th entry is unused here

f = numpy.zeros([stages + 2, inventoryCapacity + 1])
x = numpy.zeros([stages + 1, inventoryCapacity + 1], dtype=int)

for t in range(stages,0,-1) :

    for i in range(inventoryCapacity + 1) :
  
        minProduction = max(0, demand[t] - i)
        maxProduction = min(productionCapacity, inventoryCapacity - i + demand[t])
    
        value = hugeNumber

        for p in range(minProduction, maxProduction+1) : 
    
            j = i + p - demand[t]
            productionCost = variableCost*p
            if p > 0 :
                productionCost += setupCost
      
            moveValue = holdingCost*j + productionCost + f[t+1,j]
     
            if moveValue < value :
                value = moveValue
                bestMove = p
      
        # End of p loop
    
        f[t,i] = value
        x[t,i] = bestMove
    
    # End of i loop
  
# End of t loop

print("Optimal cost is " + str(f[1,startInventory]))

solutionString = "Production amounts:"
i = startInventory
for t in range(1,stages+1) : 
    solutionString += " " + str(x[t,i])
    i = i + x[t,i] - demand[t]
 
print(solutionString)
print(f)
print(x)

Optimal cost is 20.0
Production amounts: 1 5 0 4
[[ 0.   0.   0.   0.   0. ]
 [20.  16.  15.5 15.  13.5]
 [16.  15.  14.  12.  10.5]
 [12.  10.   7.   6.5  6. ]
 [ 7.   6.   5.   4.   0. ]
 [ 0.   0.   0.   0.   0. ]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [5 4 3 0 0]
 [2 5 0 0 0]
 [4 3 2 1 0]]
